// generated by agents/b19/gen_data.py from the Sayari source catalogue (lookup_data_sources), b11 TRC-23 blind-spot map,
// and UN Comtrade aggregate rows (corrected 10:19). file:// pages cannot fetch JSON.
window.COVERAGE = {
 "view": "coverage",
 "meaning": {
  "own": "has its own trade records in Sayari (the country's customs data is a source)",
  "partners": "seen only through partners' records (nobody on its own side reports)",
  "none": "not in our data (no own trade source; not checked further)"
 },
 "catalogue_file": "pulls/sayari/20260925T132800Z_lookup_data_sources.json",
 "countries": {
  "AFG": {
   "coverage": "own",
   "own_sources": [
    "Afghanistan Imports & Exports (January 2024 - Present)"
   ],
   "source_file": "pulls/sayari/20260925T132800Z_lookup_data_sources.json",
   "num": "004"
  },
  "ARG": {
   "coverage": "own",
   "own_sources": [
    "Argentina Imports & Exports (January 2022 - Present)"
   ],
   "source_file": "pulls/sayari/20260925T132800Z_lookup_data_sources.json",
   "num": "032"
  },
  "AUS": {
   "coverage": "own",
   "own_sources": [
    "Australia Imports & Exports (January 2023 - Present)"
   ],
   "source_file": "pulls/sayari/20260925T132800Z_lookup_data_sources.json",
   "num": "036"
  },
  "AUT": {
   "coverage": "own",
   "own_sources": [
    "Austria Imports & Exports (January 2023 - Present)"
   ],
   "source_file": "pulls/sayari/20260925T132800Z_lookup_data_sources.json",
   "num": "040"
  },
  "BGD": {
   "coverage": "own",
   "own_sources": [
    "Bangladesh Imports & Exports (January 2023 - Present)"
   ],
   "source_file": "pulls/sayari/20260925T132800Z_lookup_data_sources.json",
   "num": "050"
  },
  "BEL": {
   "coverage": "own",
   "own_sources": [
    "Belgium Imports & Exports (January 2023 - Present)"
   ],
   "source_file": "pulls/sayari/20260925T132800Z_lookup_data_sources.json",
   "num": "056"
  },
  "BOL": {
   "coverage": "own",
   "own_sources": [
    "Bolivia Imports & Exports (June 2024 - Present)"
   ],
   "source_file": "pulls/sayari/20260925T132800Z_lookup_data_sources.json",
   "num": "068"
  },
  "BWA": {
   "coverage": "own",
   "own_sources": [
    "Botswana Imports & Exports (January 2023 - Present)"
   ],
   "source_file": "pulls/sayari/20260925T132800Z_lookup_data_sources.json",
   "num": "072"
  },
  "BRA": {
   "coverage": "own",
   "own_sources": [
    "Brazil Imports & Exports (2022)"
   ],
   "source_file": "pulls/sayari/20260925T132800Z_lookup_data_sources.json",
   "num": "076"
  },
  "BGR": {
   "coverage": "own",
   "own_sources": [
    "Bulgaria Imports & Exports (January 2023 - Present)"
   ],
   "source_file": "pulls/sayari/20260925T132800Z_lookup_data_sources.json",
   "num": "100"
  },
  "CMR": {
   "coverage": "own",
   "own_sources": [
    "Cameroon Imports & Exports (January 2024 - present)"
   ],
   "source_file": "pulls/sayari/20260925T132800Z_lookup_data_sources.json",
   "num": "120"
  },
  "CHL": {
   "coverage": "own",
   "own_sources": [
    "Chile Imports & Exports (January 2022 - Present)"
   ],
   "source_file": "pulls/sayari/20260925T132800Z_lookup_data_sources.json",
   "num": "152"
  },
  "CHN": {
   "coverage": "own",
   "own_sources": [
    "China Imports & Exports (2022 - Present)"
   ],
   "source_file": "pulls/sayari/20260925T132800Z_lookup_data_sources.json",
   "num": "156"
  },
  "COL": {
   "coverage": "own",
   "own_sources": [
    "Colombia Imports & Exports (2008-2020)",
    "Colombia Imports & Exports (January 2022 - Present)"
   ],
   "source_file": "pulls/sayari/20260925T132800Z_lookup_data_sources.json",
   "num": "170"
  },
  "CRI": {
   "coverage": "own",
   "own_sources": [
    "Costa Rica Imports & Exports (January 2022 - Present)"
   ],
   "source_file": "pulls/sayari/20260925T132800Z_lookup_data_sources.json",
   "num": "188"
  },
  "HRV": {
   "coverage": "own",
   "own_sources": [
    "Croatia Imports & Exports (February 2023 - Present)"
   ],
   "source_file": "pulls/sayari/20260925T132800Z_lookup_data_sources.json",
   "num": "191"
  },
  "CYP": {
   "coverage": "own",
   "own_sources": [
    "Cyprus Imports & Exports (February 2023 - Present)"
   ],
   "source_file": "pulls/sayari/20260925T132800Z_lookup_data_sources.json",
   "num": "196"
  },
  "CZE": {
   "coverage": "own",
   "own_sources": [
    "Czech Republic Imports & Exports (January 2023 - Present)"
   ],
   "source_file": "pulls/sayari/20260925T132800Z_lookup_data_sources.json",
   "num": "203"
  },
  "COD": {
   "coverage": "own",
   "own_sources": [
    "Democratic Republic of the Congo Imports & Exports (January 2024 - Present)"
   ],
   "source_file": "pulls/sayari/20260925T132800Z_lookup_data_sources.json",
   "num": "180"
  },
  "DNK": {
   "coverage": "own",
   "own_sources": [
    "Denmark Imports & Exports (January 2023 - Present)"
   ],
   "source_file": "pulls/sayari/20260925T132800Z_lookup_data_sources.json",
   "num": "208"
  },
  "ECU": {
   "coverage": "own",
   "own_sources": [
    "Ecuador Imports & Exports (January 2022 - Present)"
   ],
   "source_file": "pulls/sayari/20260925T132800Z_lookup_data_sources.json",
   "num": "218"
  },
  "EST": {
   "coverage": "own",
   "own_sources": [
    "Estonia Imports & Exports (February 2023 - Present)"
   ],
   "source_file": "pulls/sayari/20260925T132800Z_lookup_data_sources.json",
   "num": "233"
  },
  "ETH": {
   "coverage": "own",
   "own_sources": [
    "Ethiopia Imports & Exports (January 2023 - Present)"
   ],
   "source_file": "pulls/sayari/20260925T132800Z_lookup_data_sources.json",
   "num": "231"
  },
  "FIN": {
   "coverage": "own",
   "own_sources": [
    "Finland Imports & Exports (January 2023 - Present)"
   ],
   "source_file": "pulls/sayari/20260925T132800Z_lookup_data_sources.json",
   "num": "246"
  },
  "FRA": {
   "coverage": "own",
   "own_sources": [
    "France Imports & Exports (January 2023 - Present)"
   ],
   "source_file": "pulls/sayari/20260925T132800Z_lookup_data_sources.json",
   "num": "250"
  },
  "DEU": {
   "coverage": "own",
   "own_sources": [
    "Germany Imports & Exports (January 2023 - Present)"
   ],
   "source_file": "pulls/sayari/20260925T132800Z_lookup_data_sources.json",
   "num": "276"
  },
  "GHA": {
   "coverage": "own",
   "own_sources": [
    "Ghana Imports (January 2023 - Present)"
   ],
   "source_file": "pulls/sayari/20260925T132800Z_lookup_data_sources.json",
   "num": "288"
  },
  "GRC": {
   "coverage": "own",
   "own_sources": [
    "Greece Imports & Exports (February 2023 - Present)"
   ],
   "source_file": "pulls/sayari/20260925T132800Z_lookup_data_sources.json",
   "num": "300"
  },
  "HUN": {
   "coverage": "own",
   "own_sources": [
    "Hungary Imports & Exports (January 2023 - Present)"
   ],
   "source_file": "pulls/sayari/20260925T132800Z_lookup_data_sources.json",
   "num": "348"
  },
  "IND": {
   "coverage": "own",
   "own_sources": [
    "India Imports & Exports (January 2023 - Present)"
   ],
   "source_file": "pulls/sayari/20260925T132800Z_lookup_data_sources.json",
   "num": "356"
  },
  "IDN": {
   "coverage": "own",
   "own_sources": [
    "Indonesia Imports & Exports (January 2019 - Present)"
   ],
   "source_file": "pulls/sayari/20260925T132800Z_lookup_data_sources.json",
   "num": "360"
  },
  "IRL": {
   "coverage": "own",
   "own_sources": [
    "Ireland Imports & Exports (January 2023 - Present)"
   ],
   "source_file": "pulls/sayari/20260925T132800Z_lookup_data_sources.json",
   "num": "372"
  },
  "ITA": {
   "coverage": "own",
   "own_sources": [
    "Italy Imports & Exports (February 2023 - Present)"
   ],
   "source_file": "pulls/sayari/20260925T132800Z_lookup_data_sources.json",
   "num": "380"
  },
  "CIV": {
   "coverage": "own",
   "own_sources": [
    "Ivory Coast Imports & Exports (January 2023 - Present)"
   ],
   "source_file": "pulls/sayari/20260925T132800Z_lookup_data_sources.json",
   "num": "384"
  },
  "JPN": {
   "coverage": "own",
   "own_sources": [
    "Japan Imports & Exports (January 2023 - Present)"
   ],
   "source_file": "pulls/sayari/20260925T132800Z_lookup_data_sources.json",
   "num": "392"
  },
  "KAZ": {
   "coverage": "own",
   "own_sources": [
    "Kazakhstan Imports & Exports (January 2023 - Present)"
   ],
   "source_file": "pulls/sayari/20260925T132800Z_lookup_data_sources.json",
   "num": "398",
   "note": "own trade source starts January 2023; most Kazakhstan-to-Russia chip records are from 2022",
   "mirror": {
    "unit": "US$ million, declared exports of chips (HS 8542) to Russia, aggregate rows only (UN Comtrade)",
    "values": {
     "2019": 0.33,
     "2020": 0.18,
     "2021": 0.25,
     "2022": 18.26,
     "2023": 15.61,
     "2024": 0.41
    },
    "source_file": "pulls/comtrade/8542_exports_to_russia_2019_2024_AGGREGATE.json"
   }
  },
  "KEN": {
   "coverage": "own",
   "own_sources": [
    "Kenya Imports (January 2024 - Present)"
   ],
   "source_file": "pulls/sayari/20260925T132800Z_lookup_data_sources.json",
   "num": "404"
  },
  "LVA": {
   "coverage": "own",
   "own_sources": [
    "Latvia Imports & Exports (January 2023 - Present)"
   ],
   "source_file": "pulls/sayari/20260925T132800Z_lookup_data_sources.json",
   "num": "428"
  },
  "LSO": {
   "coverage": "own",
   "own_sources": [
    "Lesotho Imports & Exports (January 2023 - Present)"
   ],
   "source_file": "pulls/sayari/20260925T132800Z_lookup_data_sources.json",
   "num": "426"
  },
  "LBR": {
   "coverage": "own",
   "own_sources": [
    "Liberia Imports & Exports (January 2024 - present)"
   ],
   "source_file": "pulls/sayari/20260925T132800Z_lookup_data_sources.json",
   "num": "430"
  },
  "LTU": {
   "coverage": "own",
   "own_sources": [
    "Lithuania Imports & Exports (January 2023 - Present)"
   ],
   "source_file": "pulls/sayari/20260925T132800Z_lookup_data_sources.json",
   "num": "440"
  },
  "LUX": {
   "coverage": "own",
   "own_sources": [
    "Luxembourg Imports & Exports (January 2023 - Present)"
   ],
   "source_file": "pulls/sayari/20260925T132800Z_lookup_data_sources.json",
   "num": "442"
  },
  "MWI": {
   "coverage": "own",
   "own_sources": [
    "Malawi Imports & Exports (January 2024 - present)"
   ],
   "source_file": "pulls/sayari/20260925T132800Z_lookup_data_sources.json",
   "num": "454"
  },
  "MYS": {
   "coverage": "own",
   "own_sources": [
    "Malaysia Imports & Exports (January 2025 - February 2026)"
   ],
   "source_file": "pulls/sayari/20260925T132800Z_lookup_data_sources.json",
   "num": "458"
  },
  "MLT": {
   "coverage": "own",
   "own_sources": [
    "Malta Imports & Exports (March 2023 - Present)"
   ],
   "source_file": "pulls/sayari/20260925T132800Z_lookup_data_sources.json",
   "num": "470"
  },
  "MEX": {
   "coverage": "own",
   "own_sources": [
    "Mexico Imports & Exports (January 2022 - Present)"
   ],
   "source_file": "pulls/sayari/20260925T132800Z_lookup_data_sources.json",
   "num": "484"
  },
  "MDA": {
   "coverage": "own",
   "own_sources": [
    "Moldova Imports & Exports (January 2023 - May 2023)"
   ],
   "source_file": "pulls/sayari/20260925T132800Z_lookup_data_sources.json",
   "num": "498"
  },
  "NAM": {
   "coverage": "own",
   "own_sources": [
    "Namibia Imports & Exports (January 2023 - Present)"
   ],
   "source_file": "pulls/sayari/20260925T132800Z_lookup_data_sources.json",
   "num": "516"
  },
  "NLD": {
   "coverage": "own",
   "own_sources": [
    "Netherlands Imports & Exports (January 2023 - Present)"
   ],
   "source_file": "pulls/sayari/20260925T132800Z_lookup_data_sources.json",
   "num": "528"
  },
  "NIC": {
   "coverage": "own",
   "own_sources": [
    "Nicaragua Imports & Exports (January 2024 - December 2025)"
   ],
   "source_file": "pulls/sayari/20260925T132800Z_lookup_data_sources.json",
   "num": "558"
  },
  "NGA": {
   "coverage": "own",
   "own_sources": [
    "Nigeria Imports & Exports (January 2023 - Present)"
   ],
   "source_file": "pulls/sayari/20260925T132800Z_lookup_data_sources.json",
   "num": "566"
  },
  "PAK": {
   "coverage": "own",
   "own_sources": [
    "Pakistan Imports & Exports (January 2023 - Present)",
    "Pakistan Imports (2011-2021)"
   ],
   "source_file": "pulls/sayari/20260925T132800Z_lookup_data_sources.json",
   "num": "586"
  },
  "PAN": {
   "coverage": "own",
   "own_sources": [
    "Panama Imports & Exports (January 2022 - Present)"
   ],
   "source_file": "pulls/sayari/20260925T132800Z_lookup_data_sources.json",
   "num": "591"
  },
  "PRY": {
   "coverage": "own",
   "own_sources": [
    "Paraguay Imports & Exports (January 2022 - Present)"
   ],
   "source_file": "pulls/sayari/20260925T132800Z_lookup_data_sources.json",
   "num": "600"
  },
  "PER": {
   "coverage": "own",
   "own_sources": [
    "Peru Imports & Exports (January 2023 - Present)"
   ],
   "source_file": "pulls/sayari/20260925T132800Z_lookup_data_sources.json",
   "num": "604"
  },
  "PHL": {
   "coverage": "own",
   "own_sources": [
    "Philippines Imports & Exports (January 2023 - Present)"
   ],
   "source_file": "pulls/sayari/20260925T132800Z_lookup_data_sources.json",
   "num": "608"
  },
  "POL": {
   "coverage": "own",
   "own_sources": [
    "Poland Imports & Exports (January 2023 - Present)"
   ],
   "source_file": "pulls/sayari/20260925T132800Z_lookup_data_sources.json",
   "num": "616"
  },
  "PRT": {
   "coverage": "own",
   "own_sources": [
    "Portugal Imports & Exports (January 2023 - Present)"
   ],
   "source_file": "pulls/sayari/20260925T132800Z_lookup_data_sources.json",
   "num": "620"
  },
  "ROU": {
   "coverage": "own",
   "own_sources": [
    "Romania Imports & Exports (January 2023 - Present)"
   ],
   "source_file": "pulls/sayari/20260925T132800Z_lookup_data_sources.json",
   "num": "642"
  },
  "RUS": {
   "coverage": "own",
   "own_sources": [
    "Russia Imports & Exports (January 2022 - Present)"
   ],
   "source_file": "pulls/sayari/20260925T132800Z_lookup_data_sources.json",
   "num": "643",
   "note": "81% of chip records into Russia come from Russia's own customs data (471,206 of 582,920); Russia-side customs data thins from late 2023"
  },
  "SVK": {
   "coverage": "own",
   "own_sources": [
    "Slovakia Imports & Exports (January 2023 - Present)"
   ],
   "source_file": "pulls/sayari/20260925T132800Z_lookup_data_sources.json",
   "num": "703"
  },
  "SVN": {
   "coverage": "own",
   "own_sources": [
    "Slovenia Imports & Exports (February 2023 - Present)"
   ],
   "source_file": "pulls/sayari/20260925T132800Z_lookup_data_sources.json",
   "num": "705"
  },
  "KOR": {
   "coverage": "own",
   "own_sources": [
    "South Korea Imports & Exports (January 2021 - April 2024)",
    "South Korea Imports & Exports (January 2023 - Present)"
   ],
   "source_file": "pulls/sayari/20260925T132800Z_lookup_data_sources.json",
   "num": "410"
  },
  "ESP": {
   "coverage": "own",
   "own_sources": [
    "Spain Imports & Exports (February 2023 - Present)"
   ],
   "source_file": "pulls/sayari/20260925T132800Z_lookup_data_sources.json",
   "num": "724"
  },
  "LKA": {
   "coverage": "own",
   "own_sources": [
    "Sri Lanka Imports & Exports (January 2023 - Present)"
   ],
   "source_file": "pulls/sayari/20260925T132800Z_lookup_data_sources.json",
   "num": "144"
  },
  "SWE": {
   "coverage": "own",
   "own_sources": [
    "Sweden Imports & Exports (January 2023 - Present)"
   ],
   "source_file": "pulls/sayari/20260925T132800Z_lookup_data_sources.json",
   "num": "752"
  },
  "TZA": {
   "coverage": "own",
   "own_sources": [
    "Tanzania Imports & Exports (January 2023 - Present)"
   ],
   "source_file": "pulls/sayari/20260925T132800Z_lookup_data_sources.json",
   "num": "834"
  },
  "TUR": {
   "coverage": "own",
   "own_sources": [
    "Turkey Imports & Exports (January 2019 - September 2024)"
   ],
   "source_file": "pulls/sayari/20260925T132800Z_lookup_data_sources.json",
   "num": "792"
  },
  "UGA": {
   "coverage": "own",
   "own_sources": [
    "Uganda Imports & Exports (January 2023 - Present)"
   ],
   "source_file": "pulls/sayari/20260925T132800Z_lookup_data_sources.json",
   "num": "800"
  },
  "GBR": {
   "coverage": "own",
   "own_sources": [
    "UK HM Revenue & Customs Traders Database",
    "UK Imports & Exports (January 2023 - Present)"
   ],
   "source_file": "pulls/sayari/20260925T132800Z_lookup_data_sources.json",
   "num": "826"
  },
  "UKR": {
   "coverage": "own",
   "own_sources": [
    "Ukraine Imports & Exports (January 2023 - Present)"
   ],
   "source_file": "pulls/sayari/20260925T132800Z_lookup_data_sources.json",
   "num": "804"
  },
  "URY": {
   "coverage": "own",
   "own_sources": [
    "Uruguay Imports & Exports (January 2023 - Present)"
   ],
   "source_file": "pulls/sayari/20260925T132800Z_lookup_data_sources.json",
   "num": "858"
  },
  "USA": {
   "coverage": "own",
   "own_sources": [
    "USA Imports (2021 - Present)"
   ],
   "source_file": "pulls/sayari/20260925T132800Z_lookup_data_sources.json",
   "num": "840"
  },
  "UZB": {
   "coverage": "own",
   "own_sources": [
    "Uzbekistan Imports & Exports (January 2022 - Present)"
   ],
   "source_file": "pulls/sayari/20260925T132800Z_lookup_data_sources.json",
   "num": "860"
  },
  "VEN": {
   "coverage": "own",
   "own_sources": [
    "Venezuela Imports & Exports (January 2022 - August 2024)"
   ],
   "source_file": "pulls/sayari/20260925T132800Z_lookup_data_sources.json",
   "num": "862"
  },
  "VNM": {
   "coverage": "own",
   "own_sources": [
    "Vietnam Imports & Exports (January 2019 - Present)"
   ],
   "source_file": "pulls/sayari/20260925T132800Z_lookup_data_sources.json",
   "num": "704"
  },
  "ZWE": {
   "coverage": "own",
   "own_sources": [
    "Zimbabwe Imports & Exports (January 2023 - June 2023)"
   ],
   "source_file": "pulls/sayari/20260925T132800Z_lookup_data_sources.json",
   "num": "716"
  },
  "KGZ": {
   "coverage": "partners",
   "own_sources": [],
   "source_file": "pulls/sayari/20260925T132800Z_lookup_data_sources.json",
   "note": "no import/export source of its own in Sayari: seen only when the other side reports",
   "num": "417",
   "mirror": {
    "unit": "US$ million, declared exports of chips (HS 8542) to Russia, aggregate rows only (UN Comtrade)",
    "values": {
     "2019": 0.0,
     "2020": 0.0,
     "2021": 0.01,
     "2022": 0.66,
     "2023": 13.53,
     "2024": 1.33
    },
    "source_file": "pulls/comtrade/8542_exports_to_russia_2019_2024_AGGREGATE.json"
   }
  },
  "ARM": {
   "coverage": "partners",
   "own_sources": [],
   "source_file": "pulls/sayari/20260925T132800Z_lookup_data_sources.json",
   "note": "no import/export source of its own in Sayari: seen only when the other side reports",
   "num": "051",
   "mirror": {
    "unit": "US$ million, declared exports of chips (HS 8542) to Russia, aggregate rows only (UN Comtrade)",
    "values": {
     "2019": 0.12,
     "2020": 0.01,
     "2021": 0.0,
     "2022": 13.11,
     "2023": 15.71,
     "2024": null
    },
    "source_file": "pulls/comtrade/8542_exports_to_russia_2019_2024_AGGREGATE.json"
   }
  },
  "GEO": {
   "coverage": "partners",
   "own_sources": [],
   "source_file": "pulls/sayari/20260925T132800Z_lookup_data_sources.json",
   "note": "no import/export source of its own in Sayari: seen only when the other side reports",
   "num": "268"
  },
  "BLR": {
   "coverage": "partners",
   "own_sources": [],
   "source_file": "pulls/sayari/20260925T132800Z_lookup_data_sources.json",
   "note": "no import/export source of its own in Sayari: seen only when the other side reports",
   "num": "112"
  },
  "IRN": {
   "coverage": "partners",
   "own_sources": [],
   "source_file": "pulls/sayari/20260925T132800Z_lookup_data_sources.json",
   "note": "no import/export source of its own in Sayari: seen only when the other side reports",
   "num": "364"
  },
  "HKG": {
   "coverage": "partners",
   "own_sources": [],
   "source_file": "pulls/sayari/20260925T132800Z_lookup_data_sources.json",
   "note": "no import/export source of its own in Sayari: seen only when the other side reports",
   "num": "344"
  },
  "ARE": {
   "coverage": "partners",
   "own_sources": [],
   "source_file": "pulls/sayari/20260925T132800Z_lookup_data_sources.json",
   "note": "no import/export source of its own, only a 2020 Dubai customs document set",
   "num": "784"
  },
  "TJK": {
   "coverage": "partners",
   "own_sources": [],
   "source_file": "pulls/sayari/20260925T132800Z_lookup_data_sources.json",
   "note": "no import/export source of its own in Sayari: seen only when the other side reports",
   "num": "762"
  },
  "TKM": {
   "coverage": "partners",
   "own_sources": [],
   "source_file": "pulls/sayari/20260925T132800Z_lookup_data_sources.json",
   "note": "no import/export source of its own in Sayari: seen only when the other side reports",
   "num": "795"
  },
  "AZE": {
   "coverage": "partners",
   "own_sources": [],
   "source_file": "pulls/sayari/20260925T132800Z_lookup_data_sources.json",
   "note": "no import/export source of its own in Sayari: seen only when the other side reports",
   "num": "031"
  },
  "MNG": {
   "coverage": "partners",
   "own_sources": [],
   "source_file": "pulls/sayari/20260925T132800Z_lookup_data_sources.json",
   "note": "no import/export source of its own in Sayari: seen only when the other side reports",
   "num": "496"
  },
  "SYR": {
   "coverage": "partners",
   "own_sources": [],
   "source_file": "pulls/sayari/20260925T132800Z_lookup_data_sources.json",
   "note": "no import/export source of its own in Sayari: seen only when the other side reports",
   "num": "760"
  },
  "MMR": {
   "coverage": "partners",
   "own_sources": [],
   "source_file": "pulls/sayari/20260925T132800Z_lookup_data_sources.json",
   "note": "no import/export source of its own in Sayari: seen only when the other side reports",
   "num": "104"
  },
  "CUB": {
   "coverage": "partners",
   "own_sources": [],
   "source_file": "pulls/sayari/20260925T132800Z_lookup_data_sources.json",
   "note": "no import/export source of its own in Sayari: seen only when the other side reports",
   "num": "192"
  }
 },
 "russia_thin_from": "2023-10-01",
 "status": "lead, not finding"
};
