"""Build routes_8542_rus.json (+ .js twin for file://) from saved Sayari search_trade_facets answers.

Reads ../../pulls/sayari/*_search_trade_facets.json, keeps HS 8542 shipments with arrival_country RUS
and a single departure_country filter, and writes one row per departure country. Read-only on pulls/.
Run: python extract_routes.py
"""
import glob, json, os

HERE = os.path.dirname(os.path.abspath(__file__))
PULLS = os.path.normpath(os.path.join(HERE, "..", "..", "pulls", "sayari"))
NAMES = {"KGZ": "Kyrgyzstan", "ARE": "United Arab Emirates", "KAZ": "Kazakhstan", "ARM": "Armenia",
         "TUR": "Turkey", "HKG": "Hong Kong", "DEU": "Germany", "CHN": "China", "MYS": "Malaysia",
         "TWN": "Taiwan", "THA": "Thailand", "PHL": "Philippines", "USA": "United States", "JPN": "Japan",
         "KOR": "South Korea", "UZB": "Uzbekistan", "MEX": "Mexico"}
INVASION = "2022-02-24"

def facets(path):
    d = json.load(open(path, encoding="utf-8"))
    if d.get("is_error"):
        return d.get("args", {}), None, {}
    try:
        r = json.loads(d["structured"]["result"])
    except (KeyError, TypeError, ValueError):
        return d.get("args", {}), None, {}
    return d["args"], r, {f["name"]: f["buckets"] for f in r["facets"]}

rows, overall = {}, None
for p in sorted(glob.glob(os.path.join(PULLS, "*_search_trade_facets.json"))):
    args, r, fc = facets(p)
    if r is None:
        continue
    if args.get("hs_code") != "8542" or args.get("arrival_country") != "RUS" or args.get("scope") != "shipments":
        continue
    fname = os.path.basename(p)
    if "departure_country" not in args:
        if "date_from" not in args:
            overall = {"source_file": fname, "departure_counts": {b["key"]: b["count"] for b in fc["departure_country"]}}
        continue
    iso = args["departure_country"]
    count = next((b["count"] for b in fc["departure_country"] if b["key"] == iso), None)
    first = fc["earliest_date"][0]["key"] if fc.get("earliest_date") else None
    last = fc["latest_date"][0]["key"] if fc.get("latest_date") else None
    origin = [{"iso": b["key"], "name": NAMES.get(b["key"], b["key"]), "count": b["count"]} for b in fc.get("product_origin", [])[:4]]
    rows[iso] = {
        "departure_iso": iso, "departure_name": NAMES.get(iso, iso), "arrival_iso": "RUS",
        "hs_code": "8542", "shipment_records": count,
        "first_date": first, "last_date": last,
        "starts_after_invasion": bool(first and first > INVASION),
        "made_in_top": origin,
        "source_file": fname, "source_vendor": "Sayari", "source_tool": "search_trade_facets",
        "status": "lead, not finding",
    }

order = sorted(rows.values(), key=lambda x: (not x["starts_after_invasion"], -(x["shipment_records"] or 0)))
out = {
    "view": "routes", "question": "Which countries ship chips (HS 8542) into Russia, and since when?",
    "hs_code": "8542", "hs_label": "Electronic integrated circuits (chips)", "arrival": "Russia",
    "reference_date": {"date": INVASION, "label": "Russia's full-scale invasion of Ukraine"},
    "count_unit": "shipment records in Sayari trade data (not shipments proven, not value or volume)",
    "status": "lead, not finding",
    "overall": overall, "routes": order,
    "caveats": [
        "Counts are records in Sayari's trade data, all years the file covers; they are not values, volumes or proof of a breach.",
        "First/last dates are the earliest and latest record dates in the saved answer.",
        "The saved year-filtered answers (2021, 2023) returned the same counts as the unfiltered one, so no per-year split is shown.",
    ],
}
json.dump(out, open(os.path.join(HERE, "routes_8542_rus.json"), "w", encoding="utf-8"), ensure_ascii=False, indent=1)
open(os.path.join(HERE, "routes_8542_rus.js"), "w", encoding="utf-8").write(
    "// generated by extract_routes.py from routes_8542_rus.json (file:// pages cannot fetch JSON)\nwindow.ROUTES = "
    + json.dumps(out, ensure_ascii=False) + ";\n")
for r in order:
    print(f'{r["departure_name"]:22} {r["shipment_records"]:>8,}  {r["first_date"]}..{r["last_date"]}  after={r["starts_after_invasion"]}  {r["source_file"]}')
